apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod-secret-vol
spec:
  containers:
  - name: tomcat-container
    image: 
    volumeMounts:
    - name: test-vol
      mountPath: "/etc/confidential"
      readOnly: true
  volumes:
  - name: test-vol
    secret:
      secretName: tomcat-secret-vol
